version: "3.7"

networks:

  default:
    driver: bridge
    #enable_ipv6: false
    ipam:
      driver: default
      config:
        # If the network is duplicate with yours, change it
        - subnet: 172.16.1.0/24

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=myFlaskapp
    ports:
      - 8080:8080
  nginx:
    #build: ./nginx
    #container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
